sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 4
  - 5
  - 6
  - 7
# branches:
#   only:
#     - master
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run validate
#   - npm run check-coverage
#   - npm run build
after_success:
  - npm run report-coverage
#   - npm run semantic-release
